function C = C_q_dq( model, q, dq )
%C_Q_DQ Evaluates the matrix of Coriolis and centripetal terms C(q, dq) for 
% the WAVE prototype.
%
%    C = C_Q_DQ( MODEL, q, dq )
%       returns the value of the matrix of Coriolis and centripetal terms
%       C(q, dq) evaluated on the basis of the prototype dynamic parameters
%       for a particular value of the joint variables Q and its derivative
%       DQ.
%
%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    27-Feb-2012 21:40:03

% Centers Of Gravity (COG)
pm1 = model.cog.vehicle;
pm2 = model.cog.link;
pm3 = model.cog.wing - model.mounting.wing;

% Joint positions
a1 = model.joint.vehicle;
a2 = model.joint.link;

% Masses
m1 = model.mass.vehicle;
m2 = model.mass.link;
m3 = model.mass.wing;

% Added masses
Ma1_u  = model.added_mass.vehicle(1,1);
Ma1_w  = model.added_mass.vehicle(2,2);
Ma1_wq = model.added_mass.vehicle(2,3);
Ma1_qw = model.added_mass.vehicle(3,2);
Ma2_u = model.added_mass.link(1,1);
Ma2_w = model.added_mass.link(2,2);
Ma3_u = model.added_mass.wing(1,1);
Ma3_w = model.added_mass.wing(2,2);

% Joint variables and derivatives
q3 = q(3,:);        % Vehicle pitch           [rad]
q4 = -pi+q(4,:);    % Hull-to-arm joint angle [rad]
q5 = q(5,:);        % Arm-to-wing joint angle [rad]

dq3 = dq(3,:);      % Pitch velocity          [rad/s]
dq4 = dq(4,:);
dq5 = dq(5,:);

t91 = q3+q4;
t92 = cos(t91);
t93 = cos(q3);
t94 = a1.*t93;
t95 = a1.*t93.*(1.0./2.0);
t96 = q3+q4+q5;
t97 = cos(t96);
t98 = a2.*t92;
t99 = pm3.*t97;
t100 = a2.*t92.*(1.0./2.0);
t101 = pm3.*t97.*(1.0./2.0);
t102 = m3.*pm3.*t97;
t103 = t98+t99;
t104 = Ma3_u.*t103.*(1.0./2.0);
t105 = t100+t101;
t106 = Ma3_u.*t105;
t107 = Ma2_u.*pm2.*t92;
t108 = a2.*m3.*t92;
t109 = m2.*pm2.*t92;
t110 = t102+t104+t106+t107+t108+t109;
t111 = dq4.*t110;
t112 = Ma3_u.*pm3.*t97;
t113 = t102+t112;
t114 = dq5.*t113;
t115 = sin(t91);
t116 = sin(t96);
t117 = a2.*t115;
t118 = pm3.*t116;
t119 = a2.*t115.*(1.0./2.0);
t120 = sin(q3);
t121 = pm3.*t116.*(1.0./2.0);
t122 = m3.*pm3.*t116;
t123 = a2.*m3.*t115;
t124 = m2.*pm2.*t115;
t125 = t117+t118;
t126 = Ma3_w.*t125.*(1.0./2.0);
t127 = t119+t121;
t128 = Ma3_w.*t127;
t129 = Ma2_w.*pm2.*t115;
t130 = t122+t123+t124+t126+t128+t129;
t131 = Ma3_w.*pm3.*t116;
t132 = t122+t131;
t133 = -t94+t98+t99;
t134 = t100+t101-t95;
t135 = a1.*t120;
t136 = a1.*t120.*(1.0./2.0);
t137 = t117+t118-t135;
t138 = t119+t121-t136;
t145 = pm2.*t115;
t139 = t135-t145;
t144 = pm2.*t115.*(1.0./2.0);
t140 = t136-t144;
t141 = q4+q5;
t142 = sin(t141);
t143 = sin(q4);
t156 = pm2.*t92;
t146 = -t156+t94;
t157 = pm2.*t92.*(1.0./2.0);
t147 = -t157+t95;
t148 = pm1.^2;
t149 = a1.*m3.*pm3.*t142;
t150 = sin(q5);
t151 = a2.*m3.*pm3.*t150;
t152 = Ma3_w.*pm3.*t116.*t133.*(1.0./2.0);
t153 = Ma3_w.*pm3.*t116.*t134;
t154 = Ma3_u.*t105.*t137;
t155 = Ma3_u.*t103.*t138;
t158 = a1.*a2.*m3.*t143;
t159 = a1.*m2.*pm2.*t143;
t160 = Ma3_w.*t127.*t133;
t161 = Ma3_w.*t125.*t134;
t162 = t156-t94;
t163 = Ma2_w.*pm2.*t115.*t162.*(1.0./2.0);
t164 = t157-t95;
t165 = Ma2_w.*pm2.*t115.*t164;
t166 = Ma2_u.*pm2.*t139.*t92.*(1.0./2.0);
t167 = Ma2_u.*pm2.*t140.*t92;
t168 = -t149-t154-t155-t158-t159+t160+t161+t163+t165+t166+t167;
t169 = Ma3_u.*pm3.*t137.*t97.*(1.0./2.0);
t170 = Ma3_u.*pm3.*t138.*t97;
t171 = t149-t151-t152-t153+t169+t170;
t172 = dq5.*t171;
t173 = pm2.^2;
t174 = Ma3_u.*t103.*t127;
t175 = Ma3_u.*t105.*t125;
t176 = Ma2_u.*t115.*t173.*t92;
t178 = Ma3_w.*t103.*t127;
t179 = Ma3_w.*t105.*t125;
t180 = Ma2_w.*t115.*t173.*t92;
t177 = t174+t175+t176-t178-t179-t180;
t181 = dq4.*t177;
t182 = Ma3_w.*pm3.*t103.*t116.*(1.0./2.0);
t183 = Ma3_w.*pm3.*t105.*t116;
t185 = Ma3_u.*pm3.*t125.*t97.*(1.0./2.0);
t186 = Ma3_u.*pm3.*t127.*t97;
t184 = t151+t182+t183-t185-t186;
t187 = pm3.^2;
t188 = Ma3_u.*pm3.*t103.*t116.*(1.0./2.0);
t189 = Ma3_u.*pm3.*t105.*t116;
t191 = Ma3_w.*pm3.*t125.*t97.*(1.0./2.0);
t192 = Ma3_w.*pm3.*t127.*t97;
t190 = t151+t188+t189-t191-t192;
t193 = dq4.*t190;
t194 = Ma3_u.*t116.*t187.*t97;
t197 = Ma3_w.*t116.*t187.*t97;
t195 = t194-t197;
t196 = dq5.*t195;
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t111+t114-dq3.*(Ma3_u.*t133.*(-1.0./2.0)-Ma3_u.*t134+Ma2_u.*t146.*(1.0./2.0)+Ma2_u.*t147+Ma1_u.*pm1.*t93+a1.*m2.*t93+a1.*m3.*t93-a2.*m3.*t92+m1.*pm1.*t93-m2.*pm2.*t92-m3.*pm3.*t97),-dq4.*t130-dq5.*t132+dq3.*(-t122-t123-t124+Ma2_w.*t139.*(1.0./2.0)+Ma2_w.*t140-Ma3_w.*(t117+t118-a1.*t120).*(1.0./2.0)-Ma3_w.*(t119+t121-a1.*t120.*(1.0./2.0))+Ma1_w.*pm1.*t120+a1.*m2.*t120+a1.*m3.*t120+m1.*pm1.*t120),dq3.*(Ma1_qw.*pm1.*t120.*(1.0./2.0)+Ma1_wq.*pm1.*t120.*(1.0./2.0)+Ma3_u.*t133.*t138+Ma3_u.*t134.*t137-Ma3_w.*t133.*t138-Ma3_w.*t134.*t137-Ma2_w.*t139.*t147-Ma2_w.*t140.*t146+Ma2_u.*t146.*(t136-t144)+Ma2_u.*t147.*(t135-t145)+Ma1_u.*t120.*t148.*t93-Ma1_w.*t120.*t148.*t93)-dq5.*(t151+t152+t153-Ma3_u.*pm3.*t137.*t97.*(1.0./2.0)-Ma3_u.*pm3.*t138.*t97-a1.*m3.*pm3.*t142)+dq4.*(t149+t154+t155+t158+t159-Ma3_w.*t125.*t134-Ma3_w.*t127.*t133+Ma2_w.*pm2.*t115.*t146.*(1.0./2.0)+Ma2_w.*pm2.*t115.*t147-Ma2_u.*pm2.*t139.*t92.*(1.0./2.0)-Ma2_u.*pm2.*t140.*t92),t181+dq3.*(-t149-t158-t159-Ma3_w.*t103.*t138-Ma3_w.*t105.*t137+Ma3_u.*t125.*t134+Ma3_u.*t127.*t133+Ma2_u.*pm2.*t115.*t162.*(1.0./2.0)+Ma2_u.*pm2.*t115.*t164+Ma2_w.*pm2.*t139.*t92.*(1.0./2.0)+Ma2_w.*pm2.*t140.*t92)-dq5.*t184,t193+t196-dq3.*(t149-t151-Ma3_u.*pm3.*t116.*t133.*(1.0./2.0)-Ma3_u.*pm3.*t116.*t134+Ma3_w.*pm3.*t137.*t97.*(1.0./2.0)+Ma3_w.*pm3.*t138.*t97),t111+t114+dq3.*t110,-dq3.*t130-dq4.*t130-dq5.*t132,t172-dq3.*t168-dq4.*t168,t181+dq3.*t177-dq5.*t184,t193+t196+dq3.*t190,t114+dq3.*t113+dq4.*t113,-dq3.*t132-dq4.*t132-dq5.*t132,t172+dq3.*t171+dq4.*t171,-dq3.*t184-dq4.*t184-dq5.*t184,t196+dq3.*t195+dq4.*t195],[5, 5]);
%#eml

end

